# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8090:8090"
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:7
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=beanBoi
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb-data: